#!/usr/bin/env python3
"""Regenerate the static "All feelings" reference inside index.html.

The wheel is drawn by JavaScript, so without this section crawlers (and visitors
with JS disabled) would see none of the guide text. Run this after editing
data/emotions.json, data/emotion-guides.json or data/emotion-summaries.json:

    python3 tools/build-reference.py          # rewrite index.html in place
    python3 tools/build-reference.py --check  # exit 1 if index.html is stale

No dependencies beyond the Python 3 standard library.
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
START = "<!-- feelings-reference:start (generated by tools/build-reference.py, do not edit by hand) -->"
END = "<!-- feelings-reference:end -->"
SEP = " › "
INDENT = " " * 8

# Keep in sync with GUIDE_FIELD_META / PLEASANT_ROOTS in js/emotion-guide.js.
FIELDS = [
    ("feel", "How you might feel"),
    ("body", "What's going on in your body"),
    ("call", "What this might be a call to be"),
    ("overcome", "Ways to overcome this"),
]
PLEASANT_ROOTS = {"Joyful", "Powerful", "Peaceful"}
NURTURE_LABEL = "Ways to nurture this"


def label_of(node):
    return node if isinstance(node, str) else node["label"]


def children_of(node):
    return [] if isinstance(node, str) else node.get("children", [])


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def esc(text):
    return html.escape(text, quote=True)


def render_feeling(crumb, guide):
    root, *_, name = crumb.split(SEP)
    parent_path = SEP.join(crumb.split(SEP)[:-1])
    out = [
        f'<details class="ref-feeling" id="{slug(crumb)}">',
        "  <summary>",
        f'    <span class="ref-feeling__name">{esc(name)}</span>',
        f'    <span class="ref-feeling__path">{esc(parent_path)}</span>',
        "  </summary>",
    ]
    if guide:
        out.append("  <dl>")
        for key, label in FIELDS:
            text = (guide.get(key) or "").strip()
            if not text:
                continue
            if key == "overcome" and root in PLEASANT_ROOTS:
                label = NURTURE_LABEL
            out.append(f"    <dt>{esc(label)}</dt>")
            out.append(f"    <dd>{esc(text)}</dd>")
        out.append("  </dl>")
    else:
        out.append("  <p>No guide for this feeling yet.</p>")
    out.append(
        f'  <p><a class="ref-feeling__show" href="#wheel-mount" data-crumb="{esc(crumb)}">Show on the wheel</a></p>'
    )
    out.append("</details>")
    return out


def render_reference(segments, guides, summaries):
    out = []
    for root in segments:
        root_label = label_of(root)
        out.append(f'<section class="ref-core" id="{slug(root_label)}">')
        out.append(f"  <h3>{esc(root_label)}</h3>")
        for mid in children_of(root):
            mid_label = label_of(mid)
            out.append('  <div class="ref-group">')
            out.append(f"    <h4>{esc(mid_label)}</h4>")
            mid_summary = summaries.get(SEP.join([root_label, mid_label]), "").strip()
            if mid_summary:
                out.append(f'    <p class="ref-group__summary">{esc(mid_summary)}</p>')
            for leaf in children_of(mid):
                crumb = SEP.join([root_label, mid_label, label_of(leaf)])
                out.extend("    " + line for line in render_feeling(crumb, guides.get(crumb)))
            out.append("  </div>")
        out.append("</section>")
    return "\n".join(INDENT + line for line in out)


def main():
    segments = json.loads((ROOT / "data/emotions.json").read_text(encoding="utf-8"))["segments"]
    guides = json.loads((ROOT / "data/emotion-guides.json").read_text(encoding="utf-8"))
    summaries_path = ROOT / "data/emotion-summaries.json"
    summaries = json.loads(summaries_path.read_text(encoding="utf-8")) if summaries_path.exists() else {}

    page = INDEX.read_text(encoding="utf-8")
    if page.count(START) != 1 or page.count(END) != 1:
        sys.exit("index.html is missing the feelings-reference start/end markers")
    head, rest = page.split(START)
    _, tail = rest.split(END)
    built = f"{head}{START}\n{render_reference(segments, guides, summaries)}\n{INDENT}{END}{tail}"

    if "--check" in sys.argv[1:]:
        if built != page:
            sys.exit("index.html is stale. Run: python3 tools/build-reference.py")
        print("index.html reference is up to date")
        return
    INDEX.write_text(built, encoding="utf-8")
    print(f"Wrote feelings reference into {INDEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
